#!/bin/bash 
set -o pipefail

# TF_VERSION=$1 #Terraform CLI Version to install
# DOCTL_VERSION=$2 #Digital Ocean CLI Version to install

mkdir configs/
cat << EOF > configs/generated_config.yml
version: 2.1

jobs:
  scan_app:
    docker:
      - image: $image
    steps:
      - run : echo $test_env_var

workflows:
  scan_deploy:
    jobs:
      - scan_app: 
          context: 
            - my-context

EOF
